# ~/.config/starship.toml

format = """
[\uE0B6](fg:#1C4961)[$directory](bg:#1C4961)[\uE0B0](fg:#1C4961 bg:#2F79A1)$git_branch[\uE0B0](fg:#2F79A1 bg:#3A95C7)$git_status[\uE0B0](#3A95C7 bg:#40A9E0)$time[\uE0B0](#40A9E0 bg:none) $all$character
"""

add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[git_branch]
symbol = " "
style = "bg:#2F79A1 fg:white"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:#3A95C7 fg:white"
format = "[ $all_status$ahead_behind ]($style)"

[nodejs]
disabled = false

[username]
style_user = "bold green"
show_always = true
format = "[$user](bold green) "

[directory]
style = "bg:#1C4961 fg:white"

